" from go/vim instructions, verbatim (also, Week 1, 'Ramp up your vim skills')
set nocompatible
if filereadable("/usr/share/vim/google/google.vim")
    source /usr/share/vim/google/google.vim
endif
filetype plugin indent on

" Week 2, Format BUILD files (auto format on save)
if exists("Glug")
    Glug codefmt
    Glug codefmt-google
endif
autocmd FileType blazebuild AutoFormatBuffer

" ----------------------

set fileformats=unix,mac,dos
augroup filetypedetect
au BufNewFile,BufRead *.lsl setf lsl
augroup END
source ~/.exrc

" Enable filetype plugins
filetype plugin on
filetype indent on

" Ignore compiled files
set wildignore=*.o,*~,*.pyc,*.class,*.a,*.so

" Makes search act like search in modern browsers
set incsearch

" Set to auto read when a file is changed from the outside
set autoread

" Smarter way to move between windows "
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
" Remember info about open buffers on close
set viminfo^=%
syntax on
